/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CProductDetail;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author AKITH
 */
public class ProductDetail extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProduct
     */
    public ProductDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_a_product_id = new javax.swing.JTextField();
        txt_a_product_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_a_price = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_a_warranty = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        txt_d_product_id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_d_product_name = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_d_price = new javax.swing.JTextField();
        txt_d_warranty = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_update = new javax.swing.JButton();
        txt_u_product_id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_u_product_name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_u_price = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_u_warranty = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_close = new javax.swing.JButton();
        btn_close1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1205, 435));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Product Id            :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 37, -1, 31));

        txt_a_product_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txt_a_product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 37, 235, 31));

        txt_a_product_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_a_product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_a_product_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_a_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 86, 235, 31));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Product Name     :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 86, -1, 31));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Price                    :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 135, 134, 31));

        txt_a_price.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txt_a_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 135, 235, 31));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("Warranty            :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 184, 121, 31));

        txt_a_warranty.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(txt_a_warranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 184, 235, 31));

        btn_add.setBackground(new java.awt.Color(204, 204, 255));
        btn_add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_add.setText("Add ");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 281, 118, 32));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel20.setText("Quantity             :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 233, 121, 31));

        jSpinner1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 233, 236, 31));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 354));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_d_product_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_d_product_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_d_product_idKeyPressed(evt);
            }
        });
        jPanel2.add(txt_d_product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 37, 235, 31));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setText("Product Id            :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 37, -1, 31));

        btn_delete.setBackground(new java.awt.Color(204, 204, 255));
        btn_delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 244, 118, 32));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Product Name     :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 86, -1, 31));

        txt_d_product_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_d_product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_d_product_nameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_d_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 86, 235, 31));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel16.setText("Price                    :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 135, 127, 31));

        txt_d_price.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txt_d_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 135, 235, 31));

        txt_d_warranty.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel2.add(txt_d_warranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 181, 238, 31));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setText("Warranty            :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 181, 121, 31));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 0, -1, 354));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 700));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_update.setBackground(new java.awt.Color(204, 204, 255));
        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 239, 118, 32));

        txt_u_product_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_u_product_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_u_product_idKeyPressed(evt);
            }
        });
        jPanel3.add(txt_u_product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 37, 235, 31));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setText("Product Id            :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 37, -1, 31));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Product Name     :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 86, -1, 31));

        txt_u_product_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_u_product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_u_product_nameActionPerformed(evt);
            }
        });
        jPanel3.add(txt_u_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 86, 230, 31));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel18.setText("Price                    :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 135, 127, 31));

        txt_u_price.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(txt_u_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 135, 235, 31));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel19.setText("Warranty            :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 181, 121, 31));

        txt_u_warranty.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(txt_u_warranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 181, 235, 31));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 0, -1, 354));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 1212, 10));

        btn_close.setBackground(new java.awt.Color(204, 255, 204));
        btn_close.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 130, 40));

        btn_close1.setBackground(new java.awt.Color(204, 255, 204));
        btn_close1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_close1.setText("Reset");
        btn_close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_close1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_a_product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_a_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_a_product_nameActionPerformed

    private void txt_d_product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_d_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_d_product_nameActionPerformed

    private void txt_u_product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_u_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_u_product_nameActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try
        {
        String pid = txt_a_product_id.getText();
        String pname = txt_a_product_name.getText();
        String price = txt_a_price.getText();
        String warranty = txt_a_warranty.getText();
        int quantity = Integer.parseInt(jSpinner1.getValue().toString());
        
        CProductDetail cprodet = new CProductDetail();
        cprodet.submitproductdetail(pid,pname,price,warranty,quantity);
    }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Enter Values");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try
        {
            String dpid = txt_d_product_id.getText();
        CProductDetail cprodel = new CProductDetail();
        cprodel.deletetproduct(dpid);
        }
        catch(Exception e)
                
        {
            JOptionPane.showMessageDialog(rootPane, "Enter Values");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_d_product_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_d_product_idKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            try
            {
                String pid = txt_d_product_id.getText();
                CProductDetail delpro = new CProductDetail();
                ResultSet rst = delpro.searchById(pid);
                
                if(rst.next() == false)
                {
                    JOptionPane.showMessageDialog(this, "Please Enter A Valid Product Id");
                }
                   else
                {
                    String dpname = rst.getString("item_name");
                    String dprice = rst.getString("price");
                    String dwarranty = rst.getString("warranty");
                    
                    txt_d_product_name.setText(dpname.trim());
                    txt_d_price.setText(dprice.trim());
                    txt_d_warranty.setText(dwarranty.trim());                
                }
                
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }//GEN-LAST:event_txt_d_product_idKeyPressed

    private void txt_u_product_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_u_product_idKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            try
            {
                String pid = txt_u_product_id.getText();
                CProductDetail delpro = new CProductDetail();
                ResultSet rst = delpro.searchById(pid);
                
                if(rst.next() == false)
                {
                    JOptionPane.showMessageDialog(this, "Please Enter A Valid Product Id");
                }
                   else
                {
                    String upname = rst.getString("item_name");
                    String uprice = rst.getString("price");
                    String uwarranty = rst.getString("warranty");
                    
                    txt_u_product_name.setText(upname.trim());
                    txt_u_price.setText(uprice);
                    txt_u_warranty.setText(uwarranty.trim());                
                }
                
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }//GEN-LAST:event_txt_u_product_idKeyPressed

    private void btn_close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_close1ActionPerformed
        setVisible(false);
        new ProductDetail().setVisible(true);
    }//GEN-LAST:event_btn_close1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try
        {
            String upid = txt_u_product_id.getText();
        String upname = txt_u_product_name.getText();
        String uprice = txt_u_price.getText();
        String uwarranty = txt_u_warranty.getText();
        
        CProductDetail cproup = new CProductDetail();
        cproup.updateproduct(upid,upname,uprice,uwarranty);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Enter Values");
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public void pd() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_close1;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField txt_a_price;
    private javax.swing.JTextField txt_a_product_id;
    private javax.swing.JTextField txt_a_product_name;
    private javax.swing.JTextField txt_a_warranty;
    private javax.swing.JTextField txt_d_price;
    private javax.swing.JTextField txt_d_product_id;
    private javax.swing.JTextField txt_d_product_name;
    private javax.swing.JTextField txt_d_warranty;
    private javax.swing.JTextField txt_u_price;
    private javax.swing.JTextField txt_u_product_id;
    private javax.swing.JTextField txt_u_product_name;
    private javax.swing.JTextField txt_u_warranty;
    // End of variables declaration//GEN-END:variables
}
