/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CTotalBill;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author AKITH
 */
public class TotalBill extends javax.swing.JFrame {
int total;
    /**
     * Creates new form TotalBill
     */
    public TotalBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_payment = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_balance = new javax.swing.JTextField();
        btn_total = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_bill = new javax.swing.JTextArea();
        btn_print_bill = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        btn_create_bill = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_product_name = new javax.swing.JTextField();
        sp_quantity = new javax.swing.JSpinner();
        txt_price = new javax.swing.JTextField();
        txt_warranty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_product_id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_calculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billing");
        setLocation(new java.awt.Point(340, 130));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Total                   :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 42, 122, 31));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Payment             :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 85, 122, 31));

        txt_total.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 42, 230, 31));

        txt_payment.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paymentActionPerformed(evt);
            }
        });
        jPanel1.add(txt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 85, 230, 31));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("Balance               :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 128, 122, 31));

        txt_balance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_balanceActionPerformed(evt);
            }
        });
        jPanel1.add(txt_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 128, 230, 31));

        btn_total.setBackground(new java.awt.Color(204, 204, 255));
        btn_total.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_total.setText("Total");
        btn_total.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_totalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 292, 440, 220));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_bill.setColumns(20);
        txt_bill.setRows(5);
        jScrollPane1.setViewportView(txt_bill);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 380, 410));

        btn_print_bill.setBackground(new java.awt.Color(204, 204, 255));
        btn_print_bill.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_print_bill.setText("Print Bill");
        btn_print_bill.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_print_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_print_billActionPerformed(evt);
            }
        });
        jPanel2.add(btn_print_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 120, -1));

        btn_close.setBackground(new java.awt.Color(204, 204, 255));
        btn_close.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_close.setText("Close");
        btn_close.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 120, -1));

        btn_create_bill.setBackground(new java.awt.Color(204, 204, 255));
        btn_create_bill.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_create_bill.setText("Create Bill");
        btn_create_bill.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_create_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_create_billActionPerformed(evt);
            }
        });
        jPanel2.add(btn_create_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 0, 402, 512));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_product_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_product_nameActionPerformed(evt);
            }
        });
        jPanel3.add(txt_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 67, 250, 31));

        sp_quantity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sp_quantity.setValue(1);
        jPanel3.add(sp_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 202, 250, 31));

        txt_price.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 110, 250, 31));

        txt_warranty.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(txt_warranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 159, 250, 31));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Price                    :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 110, 130, 31));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("Warranty            :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 159, 121, 31));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Product Name     :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 67, -1, 31));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Quantity              :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 202, -1, 31));

        txt_product_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_product_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_product_idKeyPressed(evt);
            }
        });
        jPanel3.add(txt_product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 24, 250, 31));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Product Id            :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, 31));

        btn_calculate.setBackground(new java.awt.Color(204, 204, 255));
        btn_calculate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_calculate.setText("Calculate");
        btn_calculate.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 120, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
       try{
        int quantity = (int) sp_quantity.getValue();
        int uprice = Integer.parseInt(txt_price.getText());
        
        CTotalBill ccalc = new CTotalBill();
        
        total=total+ccalc.Calculatebill(uprice,quantity);
        txt_total.setText(String.valueOf(total));
        txt_product_id.setText("");
        txt_product_name.setText("");
        txt_price.setText("");
        txt_warranty.setText("");
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(rootPane,"Please Enter Values");
    }//GEN-LAST:event_btn_calculateActionPerformed
    }
    private void txt_product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_product_nameActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_paymentActionPerformed

    private void txt_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_balanceActionPerformed

    private void btn_print_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print_billActionPerformed
        try 
        {
            txt_bill.print();
        }   
        catch (PrinterException e) 
        {
            JOptionPane.showMessageDialog(rootPane,"");
        }
    }//GEN-LAST:event_btn_print_billActionPerformed

    private void btn_create_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_create_billActionPerformed
        String tot = txt_total.getText();
        String pay = txt_payment.getText();
        String balance = txt_balance.getText();



        txt_bill.setText(txt_bill.getText() + "\n");
        txt_bill.setText(txt_bill.getText() + "\t" +"              ********************************"+"\n");
        txt_bill.setText(txt_bill.getText() + "\t" +"                               Recipt             \n");
        txt_bill.setText(txt_bill.getText() + "\t" +"               ********************************"+"\n");
        txt_bill.setText(txt_bill.getText() + "\n");

       txt_bill.setText(txt_bill.getText()+"\t" + "Product" + "\t" + "Price" +  "\t" +"Amount\n");


        txt_bill.setText(txt_bill.getText() + "\n");
        txt_bill.setText(txt_bill.getText() + "\n");

        txt_bill.setText(txt_bill.getText() + "\t " + "Subtotal:" +"\t "+ tot + "\n");
        txt_bill.setText(txt_bill.getText() + "\t " + "Payment :" +"\t" + pay + "\n");
        txt_bill.setText(txt_bill.getText() + "\t " + "Balance :" +"\t" + balance + "\n");

        txt_bill.setText(txt_bill.getText() + "\n");

        txt_bill.setText(txt_bill.getText() + "\n");
        txt_bill.setText(txt_bill.getText() + "\n");
        txt_bill.setText(txt_bill.getText() + "\n");
        txt_bill.setText(txt_bill.getText() + "                           ******      Thank You Come Again      ******  \n");  
    }//GEN-LAST:event_btn_create_billActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void txt_product_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_product_idKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            try
            {
                String pid = txt_product_id.getText();
                CTotalBill totbill = new CTotalBill();
                ResultSet rst = totbill.searchById(pid);
                
                if(rst.next() == false)
                {
                    JOptionPane.showMessageDialog(this, "Please Enter A Valid Product Id");
                }
                   else
                {
                    String pname = rst.getString("item_name");
                    String price = rst.getString("price");
                    String warranty = rst.getString("warranty");
                    
                    txt_product_name.setText(pname.trim());
                    txt_price.setText(price.trim());
                    txt_warranty.setText(warranty.trim()); 
                    
                }  
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }//GEN-LAST:event_txt_product_idKeyPressed

    private void btn_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_totalActionPerformed
        try
        {
        int tot = Integer.parseInt(txt_total.getText());
        int payment = Integer.parseInt(txt_payment.getText());
        
        int Balance;       
        Balance = payment - tot;
        txt_balance.setText(String.valueOf(Balance));
        }
       catch(NumberFormatException e)
        {
           JOptionPane.showMessageDialog(rootPane,"Please Enter Payment");
        }  
    }//GEN-LAST:event_btn_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public void tot() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TotalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TotalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TotalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TotalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TotalBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_create_bill;
    private javax.swing.JButton btn_print_bill;
    private javax.swing.JButton btn_total;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner sp_quantity;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextArea txt_bill;
    private javax.swing.JTextField txt_payment;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_product_id;
    private javax.swing.JTextField txt_product_name;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_warranty;
    // End of variables declaration//GEN-END:variables
}
